info:
  contact: {}
  description: 尝试swagger
  title: Go-Web开发记录
  version: 0.0.1
paths:
  /index:
    get:
      consumes:
      - application/json
      description: 用来测试swagger
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 测试index
      tags:
      - ""
swagger: "2.0"
